// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.4
// Project name: Smartwatch

#ifndef _SMARTWATCH_UI_H
#define _SMARTWATCH_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
void sec_Animation(lv_obj_t * TargetObject, int delay);
void min_Animation(lv_obj_t * TargetObject, int delay);
void hour_Animation(lv_obj_t * TargetObject, int delay);
void left_Animation(lv_obj_t * TargetObject, int delay);
void right_Animation(lv_obj_t * TargetObject, int delay);
void opa_on_Animation(lv_obj_t * TargetObject, int delay);
void dots_Animation(lv_obj_t * TargetObject, int delay);
void top_Animation(lv_obj_t * TargetObject, int delay);
void cloud_Animation(lv_obj_t * TargetObject, int delay);
void blood2_Animation(lv_obj_t * TargetObject, int delay);
void blood1_Animation(lv_obj_t * TargetObject, int delay);
void heart_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_sflash
void ui_sflash_screen_init(void);
void ui_event_sflash(lv_event_t * e);
extern lv_obj_t * ui_sflash;
extern lv_obj_t * ui_bg_sflash;
// SCREEN: ui_scr1
void ui_scr1_screen_init(void);
void ui_event_scr1(lv_event_t * e);
extern lv_obj_t * ui_scr1;
extern lv_obj_t * ui_bg_1;
// SCREEN: ui_scr2
void ui_scr2_screen_init(void);
void ui_event_scr2(lv_event_t * e);
extern lv_obj_t * ui_scr2;
extern lv_obj_t * ui_bg_2;
// SCREEN: ui_scr3
void ui_scr3_screen_init(void);
void ui_event_scr3(lv_event_t * e);
extern lv_obj_t * ui_scr3;
extern lv_obj_t * ui_bg_3;
// SCREEN: ui_scr4
void ui_scr4_screen_init(void);
void ui_event_scr4(lv_event_t * e);
extern lv_obj_t * ui_scr4;
extern lv_obj_t * ui_bg_4;
// SCREEN: ui_scr5
void ui_scr5_screen_init(void);
void ui_event_scr5(lv_event_t * e);
extern lv_obj_t * ui_scr5;
extern lv_obj_t * ui_bg_5;
// SCREEN: ui_scr6
void ui_scr6_screen_init(void);
void ui_event_scr6(lv_event_t * e);
extern lv_obj_t * ui_scr6;
extern lv_obj_t * ui_bg_6;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_flash_png);    // assets\flash.png
LV_IMG_DECLARE(ui_img_sreen1_png);    // assets\sreen1.png
LV_IMG_DECLARE(ui_img_sreen2_png);    // assets\sreen2.png
LV_IMG_DECLARE(ui_img_sreen3_png);    // assets\sreen3.png
LV_IMG_DECLARE(ui_img_sreen4_png);    // assets\sreen4.png
LV_IMG_DECLARE(ui_img_sreen5_png);    // assets\sreen5.png
LV_IMG_DECLARE(ui_img_sreen6_png);    // assets\sreen6.png

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
