// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.4
// Project name: Smartwatch

#include "../ui.h"

void ui_scr6_screen_init(void)
{
    ui_scr6 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_scr6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_bg_6 = lv_img_create(ui_scr6);
    lv_img_set_src(ui_bg_6, &ui_img_sreen6_png);
    lv_obj_set_width(ui_bg_6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_bg_6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_bg_6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_bg_6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_bg_6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_bg_6, 100);

    lv_obj_add_event_cb(ui_scr6, ui_event_scr6, LV_EVENT_ALL, NULL);

}
