// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.4
// Project name: Smartwatch

#include "../ui.h"

void ui_sflash_screen_init(void)
{
    ui_sflash = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_sflash, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_bg_sflash = lv_img_create(ui_sflash);
    lv_img_set_src(ui_bg_sflash, &ui_img_flash_png);
    lv_obj_set_width(ui_bg_sflash, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_bg_sflash, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_bg_sflash, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_bg_sflash, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_bg_sflash, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_bg_sflash, 100);

    lv_obj_add_event_cb(ui_sflash, ui_event_sflash, LV_EVENT_ALL, NULL);

}
