// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.4
// Project name: Smartwatch

#include "../ui.h"

void ui_scr1_screen_init(void)
{
    ui_scr1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_scr1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_scr1, lv_color_hex(0x0E1325), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scr1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_scr1, lv_color_hex(0x112200), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_scr1, 130, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_scr1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_scr1, LV_GRAD_DIR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bg_1 = lv_img_create(ui_scr1);
    lv_img_set_src(ui_bg_1, &ui_img_sreen1_png);
    lv_obj_set_width(ui_bg_1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_bg_1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_bg_1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_bg_1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_bg_1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_bg_1, 100);

    lv_obj_add_event_cb(ui_scr1, ui_event_scr1, LV_EVENT_ALL, NULL);

}
