// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.4
// Project name: Smartwatch

#include "../ui.h"

void ui_scr3_screen_init(void)
{
    ui_scr3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_scr3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_bg_3 = lv_img_create(ui_scr3);
    lv_img_set_src(ui_bg_3, &ui_img_sreen3_png);
    lv_obj_set_width(ui_bg_3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_bg_3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_bg_3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_bg_3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_bg_3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_bg_3, 100);

    lv_obj_add_event_cb(ui_scr3, ui_event_scr3, LV_EVENT_ALL, NULL);

}
